In [1]:
import pandas as pd
import numpy as np

In [16]:
import pandas as pd
from scipy.io import arff
from sklearn.preprocessing import LabelEncoder

def ret_(df):
    pontos = df.iloc[:, :-1].values
    labels = df.iloc[:, -1].values
    label_encoder = LabelEncoder()
    labels = label_encoder.fit_transform(labels) # transforma label em numero
    K = len(np.unique(labels))

    return [K, pontos, labels]


def rice_data():
    df = arff.loadarff('./datasets/rice-cammeo-and-osmancik/Rice_Cammeo_Osmancik.arff')
    df = pd.DataFrame(df[0])

    ret = ret_(df)
    
    return ret

def banknote_data():
    df = pd.read_csv('datasets/banknote-authentication/data_banknote_authentication.txt', delimiter=',', header=None)

    ret = ret_(df) 
    return ret 

def wine_red_data():
    df = pd.read_csv('datasets/wine-quality/winequality-red.csv', delimiter=';')

    ret = ret_(df)
    return ret

def wine_white_data():
    df = pd.read_csv('datasets/wine-quality/winequality-white.csv', delimiter=';')

    ret = ret_(df)
    return ret

def abalone():
    df = pd.read_csv('datasets/abalone/abalone.data', delimiter=',', header=None)

    df[0] = df[0].map({'F':0, 'M':1})
    ret = ret_(df)
    return ret

def eletrical_stability():
    df = pd.read_csv('datasets/eletrical-stability/eletrical.csv')
    ret = ret_(df)
    return ret

eletrical_stability()

[2,
 array([[ 2.95906002e+00,  3.07988520e+00,  8.38102539e+00, ...,
          8.87444921e-01,  9.58033988e-01,  5.53474892e-02],
        [ 9.30409723e+00,  4.90252411e+00,  3.04754073e+00, ...,
          5.62139051e-01,  7.81759911e-01, -5.95746433e-03],
        [ 8.97170691e+00,  8.84842842e+00,  3.04647875e+00, ...,
          8.39444015e-01,  1.09853245e-01,  3.47087905e-03],
        ...,
        [ 2.36403419e+00,  2.84203025e+00,  8.77639096e+00, ...,
          1.49286458e-01,  1.45984032e-01, -3.18098881e-02],
        [ 9.63151069e+00,  3.99439760e+00,  2.75707093e+00, ...,
          8.89118346e-01,  8.18391326e-01,  3.77888091e-02],
        [ 6.53052662e+00,  6.78178990e+00,  4.34969522e+00, ...,
          3.78760930e-01,  9.42630833e-01,  4.52633082e-02]]),
 array([1, 0, 1, ..., 0, 1, 1])]

In [30]:
rice_data()

[2,
 array([[1.52310000e+04, 5.25578979e+02, 2.29749878e+02, ...,
         9.28882003e-01, 1.56170000e+04, 5.72895527e-01],
        [1.46560000e+04, 4.94311005e+02, 2.06020065e+02, ...,
         8.95404994e-01, 1.50720000e+04, 6.15436316e-01],
        [1.46340000e+04, 5.01122009e+02, 2.14106781e+02, ...,
         9.12118077e-01, 1.49540000e+04, 6.93258822e-01],
        ...,
        [1.24370000e+04, 4.42498993e+02, 1.83572922e+02, ...,
         8.81144345e-01, 1.26450000e+04, 6.26738548e-01],
        [9.88200000e+03, 3.92296997e+02, 1.61193985e+02, ...,
         8.74406099e-01, 1.00970000e+04, 6.59063637e-01],
        [1.14340000e+04, 4.04709991e+02, 1.61079269e+02, ...,
         8.25692177e-01, 1.15910000e+04, 8.02949429e-01]]),
 array([0, 0, 0, ..., 1, 1, 1])]

In [31]:
banknote_data()

[2,
 array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
        [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
        [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
        ...,
        [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
        [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
        [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]]),
 array([0, 0, 0, ..., 1, 1, 1])]

In [32]:
wine_data()

FileNotFoundError: [Errno 2] No such file or directory: 'wine-quality/winequality-red.csv'